// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/auth/middleware/middleware.go

// Package middleware is a generated GoMock package.
package middleware

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMiddleware is a mock of Middleware interface.
type MockMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockMiddlewareMockRecorder
}

// MockMiddlewareMockRecorder is the mock recorder for MockMiddleware.
type MockMiddlewareMockRecorder struct {
	mock *MockMiddleware
}

// NewMockMiddleware creates a new mock instance.
func NewMockMiddleware(ctrl *gomock.Controller) *MockMiddleware {
	mock := &MockMiddleware{ctrl: ctrl}
	mock.recorder = &MockMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMiddleware) EXPECT() *MockMiddlewareMockRecorder {
	return m.recorder
}

// CheckToken mocks base method.
func (m *MockMiddleware) CheckToken(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckToken", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// CheckToken indicates an expected call of CheckToken.
func (mr *MockMiddlewareMockRecorder) CheckToken(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckToken", reflect.TypeOf((*MockMiddleware)(nil).CheckToken), next)
}

// GetUserInformationContext mocks base method.
func (m *MockMiddleware) GetUserInformationContext(ctx context.Context) (*UserData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInformationContext", ctx)
	ret0, _ := ret[0].(*UserData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInformationContext indicates an expected call of GetUserInformationContext.
func (mr *MockMiddlewareMockRecorder) GetUserInformationContext(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInformationContext", reflect.TypeOf((*MockMiddleware)(nil).GetUserInformationContext), ctx)
}

// InitLog mocks base method.
func (m *MockMiddleware) InitLog(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitLog", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// InitLog indicates an expected call of InitLog.
func (mr *MockMiddlewareMockRecorder) InitLog(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitLog", reflect.TypeOf((*MockMiddleware)(nil).InitLog), next)
}
